version:  '3'
services:
  datascience-notebook:
      image:  registry.orientsoft.cn/library/jupyterlab-chinese:20190329 
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/jupyter_chinese:Z
      ports:
        - ${PORT}:8888
      container_name:   jupyter_notebook
      command: "start-notebook.sh \
        --NotebookApp.password=${ACCESS_TOKEN}"
